/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4ime76l63reabcuosiq5byguhi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:c608eba9-c1f9-4c62-9aa3-8891a1ed050c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fJGvxH3oJ",
    "aws_user_pools_web_client_id": "553894mcfil4ptac6gidjtvb64",
    "oauth": {
        "domain": "unisysemployeesync079b3ac6-079b3ac6-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://unisysemployeesync/signin/",
        "redirectSignOut": "https://unisysemployeesync/singout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
